### ISSUE TITLE
Error loading the plugin `cocoapods-amimono-0.0.4`.

### ISSUE THREAD

**Issue by JayZhao** [Ruenzuo/cocoapods-amimono#12]
Error loading the plugin `cocoapods-amimono-0.0.4`.

SyntaxError - /Library/Ruby/Gems/2.0.0/gems/cocoapods-amimono-0.0.4/lib/cocoapods-amimono/integrator.rb:26: syntax error, unexpected ')'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-amimono-0.0.4/lib/cocoapods-amimono/integrator.rb:44: syntax error, unexpected ')'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-amimono-0.0.4/lib/cocoapods-amimono/integrator.rb:61: syntax error, unexpected ')'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-amimono-0.0.4/lib/cocoapods-amimono/integrator.rb:65: syntax error, unexpected keyword_end, expecting end-of-input
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-amimono-0.0.4/lib/cocoapods_plugin.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by Ruenzuo** [comment]
Sorry for the late reply. That looks like the system Ruby, this isn't the first time I heard that the gem doesn't work with it. Could you try using [RVM](http://rvm.io) or something similar? I'll have a look at this soon, definitively I'm doing something wrong, the gem should work with the default Ruby installation on macOS.

**Comment by giacaglia** [comment]
I had the same problem

**Comment by Ruenzuo** [comment]
This should be fixed by https://github.com/Ruenzuo/cocoapods-amimono/pull/16 and it's available now in v0.0.5. Thanks @JayZhao and @giacaglia for reporting!
