### ISSUE TITLE
#if __has_include  and pod configuration not support

### ISSUE THREAD

**Issue by pinguo-gaoshan** [Ruenzuo/cocoapods-amimono#14]
like this:
    pod 'xxxx', :configurations => ['Debug']

Undefined symbols for architecture x86_64:
  "xxxxxxxx", referenced from:
      -[*****\* ******_:] in ***_**.o

I use __has_include to resovle dependency

**Comment by Ruenzuo** [comment]
Sorry for the late reply. Could you elaborate? I made [a few changes](https://github.com/Ruenzuo/cocoapods-amimono-example/compare/master...has_include) to the example project to use pods per configuration and the include file check macro but I was not able to reproduce this on v0.0.5.

**Comment by Ruenzuo** [comment]
Closing due inactivity.
