### ISSUE TITLE
Support for cocoapods 1.2.0?

### ISSUE THREAD

**Issue by vevo-heyward-dai** [Ruenzuo/cocoapods-amimono#19]
<img width="1222" alt="screen shot 2017-02-09 at 1 02 29 am" src="https://cloud.githubusercontent.com/assets/10034863/22776240/c536e408-ee63-11e6-9cc1-ec2b9655fba4.png">

After updating to cocoapods 1.2.0, amimono no longer works. I get the above error message. Any ideas?

**Comment by Ruenzuo** [comment]
Thanks for reporting this! @dhcdht added CocoaPods 1.2.0 support on master a few days ago. You can reference master in your [Gemfile](https://github.com/Ruenzuo/cocoapods-amimono-example/blob/master/Gemfile#L4). I'll release a new version today.

**Comment by Ruenzuo** [comment]
v0.0.7 pushed to RubyGems.
