### ISSUE TITLE
Does this projet still works ?

### ISSUE THREAD

**Issue by mackoj** [Ruenzuo/cocoapods-amimono#22]
I have linker issue when I try to use it.

```
ld: file not found: 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Ruenzuo** [comment]
Yes, it works with the latest version of CocoaPods and recently I added [binary static frameworks support](https://github.com/Ruenzuo/cocoapods-amimono-example/pull/1). There's an example project [here](https://github.com/Ruenzuo/cocoapods-amimono-example).

Looks like the file list generation doesn't work with your Podfile, could you try the latest master? If the problem persist, I'm happy to help if you can provide an example project with the issue.

**Comment by mackoj** [comment]
Thanks for the quick response.

How to try it against master ? Should I install a custom version from gem ?

If I still have this issue I will provide an exemple for sure ;)

**Comment by Ruenzuo** [comment]
CocoaPods has a really nice guide on how to use it from master: [Using master CocoaPods](https://guides.cocoapods.org/using/a-gemfile.html#using-master-cocoapods), basically follow the same approach except that your `Gemfile` will look something like this:

```ruby
source "https://rubygems.org"

gem "cocoapods"
gem "cocoapods-amimono", git: "git://github.com/ruenzuo/cocoapods-amimono.git"
```
