### ISSUE TITLE
Issue when adding binary frameworks when the pod name differs from the framework name

### ISSUE THREAD

**Issue by Curtis-Halbrook** [Ruenzuo/cocoapods-amimono#25]
Cocoapods 1.2.1
Amimono 0.0.8

After upgrading to 0.0.8, we seem to be having issues with building; it fails in the Link step because it can't find a referenced framework.

`
ld: framework not found AppsFlyerFramework
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Investigating found that the framework referenced is the "AppsFlyerFramework", which is a 3rd party binary framework.  The peculiar thing is that while the Cocoapod is named AppsFlyerFramework, the actual library is called "AppsFlyerLib.framework". Others that have this same format are the Google Mobile Ads frameworks "Google-Mobile-Ads-SDK" is called "GoogleMobileAds.framework".

Looking in the generated .xcconfig file, I see this:

`OTHER_LDFLAGS = $(inherited) -ObjC -fobjc-arc -l"c++" -l"comScore" -l"sqlite3" -l"z" -framework "AVFoundation" -framework "AdSupport" -framework "AppsFlyerFramework" -framework "AppsFlyerLib" -framework "AssetsLibrary" -framework "AudioToolbox" -framework "CoreData" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CoreVideo" -framework "Foundation" -framework "GLKit" -framework "Google-Mobile-Ads-SDK" -framework "GoogleAds-IMA-iOS-SDK-For-AdMob" -framework "GoogleAppIndexing" -framework "GoogleInteractiveMediaAds" -framework "GoogleMobileAds" -framework "GoogleMobileAdsMediationMoPub" -framework "HockeySDK" -framework "ImageIO" -framework "Localytics" -framework "Mapbox" -framework "Mapbox-iOS-SDK" -framework "MediaPlayer" -framework "MessageUI" -framework "MoPubAdapter" -framework "MobileCoreServices" -framework "OpenGLES" -framework "QuartzCore" -framework "QuickLook" -framework "SafariServices" -framework "Security" -framework "StoreKit" -framework "SystemConfiguration" -framework "TWCMoatMobileAppKit" -framework "UIKit" -framework "iAd" -weak_framework "Accounts" -weak_framework "AdSupport" -weak_framework "AudioToolbox" -weak_framework "CoreGraphics" -weak_framework "CoreLocation" -weak_framework "Foundation" -weak_framework "JavaScriptCore" -weak_framework "QuartzCore" -weak_framework "SafariServices" -weak_framework "Security" -weak_framework "Social" -weak_framework "StoreKit" -weak_framework "UIKit" -weak_framework "WebKit"
`

Looking at the same file without Amimono, I see this:

`
OTHER_LDFLAGS = $(inherited) -ObjC -fobjc-arc -l"c++" -l"sqlite3" -l"z" -framework "AVFoundation" -framework "AWSCognito" -framework "AWSCore" -framework "AWSSQS" -framework "AdSupport" -framework "AirLockSDK" -framework "Alamofire" -framework "AppsFlyerLib" -framework "AssetsLibrary" -framework "AudioToolbox" -framework "Bolts" -framework "CRToast" -framework "ComScore" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CoreVideo" -framework "FBSDKCoreKit" -framework "FBSDKLoginKit" -framework "FLEX" -framework "Foundation" -framework "GCDObjC" -framework "GLKit" -framework "GRMustache" -framework "GoogleAppIndexing" -framework "GoogleInteractiveMediaAds" -framework "GoogleMobileAds" -framework "HTMLReader" -framework "HockeySDK" -framework "IOSQueryable" -framework "ISO8601DateFormatter" -framework "JRSwizzle" -framework "Localytics" -framework "MBCircularProgressBar" -framework "MMDrawerController" -framework "MMMarkdown" -framework "Mapbox" -framework "MarqueeLabel" -framework "MediaPlayer" -framework "MessageUI" -framework "MoPub" -framework "MoPubAdapter" -framework "MobileCoreServices" -framework "NSDate_TimeAgo" -framework "OpenGLES" -framework "PangeaSDK" -framework "QuartzCore" -framework "QuickLook" -framework "RxCocoa" -framework "RxDataSources" -framework "RxSwift" -framework "SDWebImage" -framework "SafariServices" -framework "Security" -framework "StoreKit" -framework "SwiftyJSON" -framework "SwiftyStoreKit" -framework "SystemConfiguration" -framework "TWCMoatMobileAppKit" -framework "TWCProfileSDK" -framework "TransitionKit" -framework "UIKit" -framework "WXCCache" -framework "WXCContentService" -framework "WXDeepLinkKit" -framework "WXNetwork" -framework "WXReports" -framework "WxIcons" -framework "iAd" -weak_framework "AdSupport" -weak_framework "JavaScriptCore" -weak_framework "SafariServices" -weak_framework "WebKit"
`

So, it looks like the core issue here is an assumption somewhere that the name of the Pod will always be the name of the Framework.

**Comment by Ruenzuo** [comment]
Thanks for reporting this!, the xcconfig file you shared was really helpful. Looks like [this](https://github.com/Ruenzuo/cocoapods-amimono/blob/master/lib/cocoapods-amimono/xcconfig_updater.rb#L17) should be more like:

```ruby
non_binary_frameworks = aggregated_target.pod_targets.select(&:should_build?).map(&:name)
xcconfig.other_linker_flags[:frameworks].reject! { |framework| non_binary_frameworks.include?(framework) }
```

I'll have something for tomorrow.

**Comment by Ruenzuo** [comment]
I've updated the [sample project](https://github.com/Ruenzuo/cocoapods-amimono-example/commit/61b86d5101cf65995c164a22250b3fd5718be84f) with `AppsFlyerFramework `. Feel free to reopen this issue if your problem persists.
