### ISSUE TITLE
when podfile contains any pod with "+" or "-" sign in title amimono patcher not working

### ISSUE THREAD

**Issue by ichina** [Ruenzuo/cocoapods-amimono#28]
you can check it on you cocoapods-amimono-example project
just add `pod 'NSObject+Rx'` or `pod 'NSAttributedString-DDHTML'` in you podfile
after app running you will get error:
`dyld: Library not loaded: @rpath/NSObject_Rx.framework/NSObject_Rx.`

i think the problem is that result framework has different name than original pod title.
all "+" and "-"  replacing with "_" underscore sign

cocoapods-amimono version is 0.0.9

**Comment by igor-makarov** [comment]
It's not just the `+` and `-` that are problematic. In some cases, the names are arbitrarily different.
I'm working on a pull request that covers all the cases by using the product_name property of the target.

**Comment by igor-makarov** [comment]
[#30](https://github.com/Ruenzuo/cocoapods-amimono/pull/30) solves this and also another issue I've encountered.

**Comment by Ruenzuo** [comment]
I'll make a release later today. Thank you @ichina and @igor-makarov.

**Comment by ichina** [comment]
awesome!!!

**Comment by Ruenzuo** [comment]
v0.0.10 pushed to RubyGems.

I've updated the [sample project](https://github.com/Ruenzuo/cocoapods-amimono-example) with NSObject+Rx.
