### ISSUE TITLE
Crash on start: "dyld: Library not loaded"

### ISSUE THREAD

**Issue by CognitiveDisson** [Ruenzuo/cocoapods-amimono#33]
Hi. Thanks for an interesting solution.
I have problems with integrating into my application.
When the application starts, crash occurs with the following message:
```
dyld: Library not loaded: @rpath/YandexMobileAds.framework/YandexMobileAds
  Referenced from: /Users/username/Library/Developer/CoreSimulator/Devices/19D4EF8E-8012-477B-8E31-154EEC209BAB/data/Containers/Bundle/Application/A569D0EF-A0D7-467A-9D48-613CCC1E7C8B/AmimonoCheck.app/AmimonoCheck
  Reason: image not found
```
To find the problem, I prepared an [example](https://github.com/CognitiveDisson/AmimonoCheck).
Podfile:
```
plugin 'cocoapods-amimono'
target 'AmimonoCheck' do
  use_frameworks!
  pod 'DevPod', :path => 'DevPod'
end
post_install do |installer|
  require 'cocoapods-amimono/patcher'
  Amimono::Patcher.patch!(installer)
end
```
DevPod.podspec:
```
  s.name                   = 'DevPod'
...
  s.platform               = :ios, '8.0'
  s.ios.deployment_target = "8.0"
  s.requires_arc = true
  s.source_files = 'View/**/*'
  s.vendored_frameworks = 'GoogleMobileAds.framework', 'MyTargetSDK.framework'
  s.dependency 'YandexMobileAds/Dynamic'
```
Similar problems have arisen with other vendored frameworks (GoogleMobileAd, MyTargetSDK) that are used in the dependencies of my project.
Would be very glad if you helped me to fix this problem or at least prompted with what it may be related.

**Comment by Ruenzuo** [comment]
Should be fixed by #34.
