### ISSUE TITLE
Support for Cocoapods 1.3?

### ISSUE THREAD

**Issue by adad184** [Ruenzuo/cocoapods-amimono#38]
![image](https://user-images.githubusercontent.com/878260/30536135-493b540e-9c2a-11e7-8319-3bfcdc54bfd0.png)

**Comment by CognitiveDisson** [comment]
HI. You can use my [PR](https://github.com/Ruenzuo/cocoapods-amimono/pull/40)

**Comment by Ruenzuo** [comment]
Closed by #40
