### ISSUE TITLE
Amimono + Test targets

### ISSUE THREAD

**Issue by beefon** [Ruenzuo/cocoapods-amimono#41]
Is there a particular reason why did you opt out targets with 'Test' word in it?

`aggregated_targets = installer.aggregate_targets.reject { |target| target.label.include? 'Test' }`

**Comment by Ruenzuo** [comment]
This has been closed by https://github.com/Ruenzuo/cocoapods-amimono/pull/42

The reason why I put this was because I thought Test target didn't need any special handle as they're not target we ship. I've seen the arguments in #42 to change this and I'm okay with it.

**Comment by beefon** [comment]
Thanks for explaining!
